name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        fleet: [balenablocks/photo-gallery-aarch64, balenablocks/photo-gallery-amd64, balenablocks/photo-gallery-armv7hf, balenablocks/photo-gallery-rpi]

    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@v0.9.0
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          environment: balena-cloud.com
          fleet: ${{ matrix.fleet }}
          versionbot: true